//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTiendaAccesorios.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdTiendaAccesoriosEntities : DbContext
    {
        public bdTiendaAccesoriosEntities()
            : base("name=bdTiendaAccesoriosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tblCiudad> tblCiudads { get; set; }
        public virtual DbSet<tblCliente> tblClientes { get; set; }
        public virtual DbSet<tblDetallePedido> tblDetallePedidoes { get; set; }
        public virtual DbSet<tblDireccionCliente> tblDireccionClientes { get; set; }
        public virtual DbSet<tblDireccionProveedor> tblDireccionProveedors { get; set; }
        public virtual DbSet<tblFormaEntrega> tblFormaEntregas { get; set; }
        public virtual DbSet<tblFormaPago> tblFormaPagoes { get; set; }
        public virtual DbSet<tblGarantia> tblGarantias { get; set; }
        public virtual DbSet<tblPedido> tblPedidoes { get; set; }
        public virtual DbSet<tblProducto> tblProductoes { get; set; }
        public virtual DbSet<tblProveedor> tblProveedors { get; set; }
        public virtual DbSet<tblTelefonoCliente> tblTelefonoClientes { get; set; }
        public virtual DbSet<tblTelefonoProveedor> tblTelefonoProveedors { get; set; }
        public virtual DbSet<tblTipoDocumento> tblTipoDocumentoes { get; set; }
        public virtual DbSet<tblTipoProducto> tblTipoProductoes { get; set; }
    }
}
