//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTiendaAccesorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblCliente
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblCliente()
        {
            this.tblDireccionClientes = new HashSet<tblDireccionCliente>();
            this.tblPedidoes = new HashSet<tblPedido>();
            this.tblTelefonoClientes = new HashSet<tblTelefonoCliente>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public int id_tipo_documento { get; set; }
        public string nro_documento { get; set; }
        public bool activo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDireccionCliente> tblDireccionClientes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblPedido> tblPedidoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblTelefonoCliente> tblTelefonoClientes { get; set; }
        public virtual tblTipoDocumento tblTipoDocumento { get; set; }
    }
}
