//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTiendaAccesorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblPedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblPedido()
        {
            this.tblDetallePedidoes = new HashSet<tblDetallePedido>();
        }
    
        public int id { get; set; }
        public int id_cliente { get; set; }
        public int id_direccion { get; set; }
        public int id_forma_entrega { get; set; }
        public int id_forma_pago { get; set; }
        public System.DateTime fecha_pedido { get; set; }
        public Nullable<System.DateTime> fecha_entrega { get; set; }
        public double total { get; set; }
        public Nullable<double> descuento { get; set; }
    
        public virtual tblCliente tblCliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallePedido> tblDetallePedidoes { get; set; }
        public virtual tblDireccionCliente tblDireccionCliente { get; set; }
        public virtual tblFormaEntrega tblFormaEntrega { get; set; }
        public virtual tblFormaPago tblFormaPago { get; set; }
    }
}
