//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiTiendaAccesorios.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tblProducto()
        {
            this.tblDetallePedidoes = new HashSet<tblDetallePedido>();
        }
    
        public int id { get; set; }
        public string nombre { get; set; }
        public string codigo { get; set; }
        public decimal valor_unitario { get; set; }
        public int id_proveedor { get; set; }
        public int id_tipo_producto { get; set; }
        public int tiempo_garantia { get; set; }
        public Nullable<double> descuento { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tblDetallePedido> tblDetallePedidoes { get; set; }
        public virtual tblProveedor tblProveedor { get; set; }
        public virtual tblTipoProducto tblTipoProducto { get; set; }
    }
}
